openapi: 3.0.3
info:
  title: The Dogs API
  description: |-
    This is a simple API all about dogs.
    
servers:
  - url: https://frozen-bayou-57322.herokuapp.com/api/

tags:
  - name: dogs
    description: Everything about Dogs
paths:
  /dogs:
    get:
      tags:
        - dogs
      summary: List of dogs
      description: Returns list of dogs
      parameters:
        - name: limit
          in: path
          description: Number of results to return (default value 10)
          required: false
          schema:
            type: integer
            format: int64
        - name: page 
          in: path
          description: Paginate through results
          required: false
          schema:
            type: integer
            format: int64
        - name: name
          in: path
          description: Name of breed that need to be considered for filter
          required: false
          schema:
            type: string
        - name: breed_group
          in: path
          description: Group of breed that need to be considered for filter
          required: false
          schema:
            type: string
        - name: temperament
          in: path
          description: Temperament of breed that need to be considered for filter
          required: false
          schema:
            type: string
        - name: origin
          in: path
          description: Origin country of breed that need to be considered for filter
          required: false
          schema:
            type: string
        - name: country_code
          in: path
          description: Country code of breed that need to be considered for filter
          required: false
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dogs'

  /dogs/{id}:
    get:
      tags:
        - dogs
      summary: Find dog by ID
      description: Returns a single dog
      operationId: getDogById
      parameters:
        - name: Id
          in: path
          description: ID of dog to return
          required: true
          schema:
            type: integer
            format: int64

      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dogs'
                   
components:
  schemas:
    Dogs:
      required:
        - name
        - photoUrls
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
        
  requestBodies:
    Dogs:
      description: Dog object that 
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Dogs'
